app/urls.py
from django.urls import path
from app.views import (
    IndexView,
    CreateTaskView,
    UpdateTaskView,
    DeleteTaskView,
    TagListView,
    CreateTagView,
    UpdateTagView,
    DeleteTagView,
    do_task,
)

app_name = "app"

urlpatterns = [
    path("", IndexView.as_view(), name="task_list"),
    path("add-task/", CreateTaskView.as_view(), name="create_task"),
    path(
        "update-task/<int:pk>/", UpdateTaskView.as_view(), name="update_task"
    ),
    path(
        "delete-task/<int:pk>/", DeleteTaskView.as_view(), name="delete_task"
    ),
    path("do-task/<int:pk>/", do_task, name="do_task"),
    path("tags/", TagListView.as_view(), name="tag_list"),
    path("add-tag/", CreateTagView.as_view(), name="add_tag"),
    path("update-tag/<int:pk>/", UpdateTagView.as_view(), name="update_tag"),
    path("delete-tag/<int:pk>/", DeleteTagView.as_view(), name="delete_tag"),
]

to_do_app/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("app.urls")),
]

app/models.py
from django.db import models


class Tag(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Task(models.Model):
    content = models.TextField()
    datetime = models.DateTimeField(auto_now_add=True)
    deadline = models.DateTimeField(null=True, blank=True)
    is_done = models.BooleanField(default=False)
    tags = models.ManyToManyField(Tag, related_name="tasks")

    class Meta:
        ordering = ["datetime", "is_done"]

app/forms.py
from django import forms

from app.models import Task, Tag


class TaskForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = ["content", "deadline", "tags"]
        widgets = {
            "deadline": forms.DateTimeInput(attrs={"type": "datetime-local"}),
            "content": forms.Textarea(attrs={"rows": 4}),
        }


class TagForm(forms.ModelForm):
    class Meta:
        model = Tag
        fields = ["name"]
        widgets = {
            "name": forms.TextInput(attrs={"type": "text"}),
        }
        widget = forms.CheckboxSelectMultiple

app/views.py
from django.shortcuts import get_object_or_404, redirect
from django.views import generic
from django.urls import reverse_lazy

from app.forms import TagForm, TaskForm
from app.models import Task, Tag


class IndexView(generic.ListView):
    model = Task
    queryset = Task.objects.prefetch_related("tags").order_by("-datetime")
    template_name = "index.html"
    context_object_name = "tasks"


class CreateTaskView(generic.CreateView):
    model = Task
    form_class = TaskForm
    success_url = reverse_lazy("app:task_list")


class UpdateTaskView(generic.UpdateView):
    model = Task
    form_class = TaskForm
    success_url = reverse_lazy("app:task_list")


class DeleteTaskView(generic.DeleteView):
    model = Task
    success_url = reverse_lazy("app:task_list")


class TagListView(generic.ListView):
    model = Tag


class CreateTagView(generic.CreateView):
    model = Tag
    fields = "__all__"
    success_url = reverse_lazy("app:tag_list")


class UpdateTagView(generic.UpdateView):
    model = Tag
    form_class = TagForm
    success_url = reverse_lazy("app:tag_list")


class DeleteTagView(generic.DeleteView):
    model = Tag
    success_url = reverse_lazy("app:tag_list")


def do_task(request, pk):
    task = get_object_or_404(Task, pk=pk)
    task.is_done = not task.is_done
    task.save()
    return redirect("/")

templates/app/tag_confirm_delete.html
{% extends "base.html" %}

{% block content %}
<div class="container mt-4">
  <h1 style="font-weight: bold">delete confirmation</h1>
  <p>delete this tag <strong>{{ object.name }}</strong>?</p>
  <form method="post">
    {% csrf_token %}
    <a href="{% url 'app:tag_list' %}" class="btn btn-info">Cancel</a>
    <button type="submit" class="btn btn-danger">Delete</button>
  </form>
</div>
{% endblock %}

templates/app/tag_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}
{% block content %}
  <form action="" method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="Save" class="btn btn-primary">
    <a href="{% url 'app:tag_list' %}" class="btn btn-info">Cancel</a>
  </form>
{% endblock %}

templates/app/tag_list.html
{% extends "base.html" %}
{% block content %}
  <div class="row">
    <div class="col-10">
      <h1 style="font-weight: 700">TAGS</h1>
    </div>
    <div class="col-2">
      <a class="btn btn-primary" href="{% url 'app:add_tag' %}">Add</a>
    </div>
  </div>
  <ul class="list-group">
    <li class="list-group-item">
      <div class="container-fluid row">
          <div class="col-4" style="font-weight: 700">Name</div>
          <div class="col-4" style="font-weight: 700">Update</div>
          <div class="col-4" style="font-weight: 700">Delete</div>
      </div>
    </li>
    {% for tag in tag_list %}
      <li class="list-group-item">
        <div class="container-fluid row">
          <div class="col-4">{{ tag.name }}</div>
          <div class="col-4">
            <a href="{% url 'app:update_tag' pk=tag.id %}">Update</a>
          </div>
          <div class="col-4">
            <a href="{% url 'app:delete_tag' pk=tag.id %}">Delete</a>
          </div>
        </div>
      </li>
    {% endfor %}
  </ul>
{% endblock %}

templates/app/task_confirm_delete.html
{% extends "base.html" %}

{% block content %}
<div class="container mt-4">
  <h1 style="font-weight: bold">delete confirmation</h1>
  <p>delete this task <strong>{{ object.content }}</strong>?</p>
  <form method="post">
    {% csrf_token %}
    <a href="{% url 'app:task_list' %}" class="btn btn-info">Cancel</a>
    <button type="submit" class="btn btn-danger">Delete</button>
  </form>
</div>
{% endblock %}

templates/app/task_form.html
{% extends "base.html" %}
{% load crispy_forms_filters %}
{% block content %}
  <form action="" method="post">
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="Create new task" class="btn btn-primary">
    <a href="{% url 'app:task_list' %}" class="btn btn-info">Cancel</a>
  </form>
{% endblock %}

templates/base.html
<!doctype html>
<html lang="en">

<head>
  {% block title %}<title>ToDo app</title>{% endblock %}
  <meta charset="UTF-8">
  <link rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" crossorigin="anonymous">
  {% load static %}
</head>

<body>
  <div class="container-fluid">
    <div class="row">
      <nav class="col-2 py-3">
        {% include 'includes/sidebar.html' %}
      </nav>
      <moin class="col-10 py-3">
        {% block content %}
        {% endblock %}
      </moin>
    </div>
  </div>
</body>
</html>

templates/includes/sidebar.html
<ul class="list-group" style="width: 100px">
  <li class="list-group-item">
    <a href="/">Home</a>
  </li>
  <li class="list-group-item">
    <a href="{% url 'app:tag_list' %}">Tags</a>
  </li>
</ul>

templates/index.html
{% extends "base.html" %}

{% block content %}
<div class="container mt-4">
  <div class="row mb-4">
    <div class="col-10">
      <h1 class="mb-4" style="font-weight: bold">TODO List</h1>
    </div>
    <div class="col-2 text-end">
      <a href="{% url 'app:create_task' %}" class="btn btn-primary">Add task</a>
    </div>
  </div>

  {% if tasks %}
  <ul class="list-group">
    {% for task in tasks %}
      <li class="list-group-item d-flex justify-content-between align-items-center">
        <div>
          <div class="d-flex align-items-center">
            <h1 style="font-weight: bold; font-size: 20px; margin-right: 10px;">{{ task.content }}</h1>
            {% if task.is_done %}
              <span class="badge bg-success" style="font-size: 16px; color: white;">Done</span>
            {% else %}
              <span class="badge bg-danger" style="font-size: 16px; color: white;">Not Done</span>
            {% endif %}
          </div>
          <small class="text-info ">Created: {{ task.datetime }}</small>
          {% if task.deadline %}
            <small class="text-danger">Deadline: {{ task.deadline|date:"M d, Y, H:i" }}</small>
          {% endif %}
          {% if task.tags.all %}
            <small class="d-block">Tags: {{ task.tags.all|join:", " }}</small>
          {% endif %}
          <a class="text-white badge bg-primary" href="{% url 'app:update_task' pk=task.id %}" style="font-size: 20px">Update</a>
          <a class="text-white badge bg-danger" href="{% url 'app:delete_task' pk=task.id %}" style="font-size: 20px; margin-top: 10px">Delete</a>
        </div>
        <a href="{% url 'app:do_task' task.pk %}" class="btn btn-sm {% if task.is_done %}btn-secondary{% else %}btn-success{% endif %}">
          {% if task.is_done %}Undo{% else %}Complete{% endif %}
        </a>
      </li>
    {% endfor %}
  </ul>
  {% else %}
  <p class="text-muted">no tasks found</p>
  {% endif %}
</div>
{% endblock %}
